-- 0001 — schema.
--
-- Tables and indexes only. The lab data is NOT in this repo (the repo is
-- public). It is loaded once from private-data/load.sql, kept with backups.
--
-- Changes from the MySQL dump:
--   * user-id columns are uuid so they can point at Supabase Auth users.
--     All were empty in the dump. Foreign keys are added in 0002.
--   * sample.strand_date is nullable: 5 legacy rows had '0000-00-00'.
--   * audit_log.related_stssn has no foreign key, so deleting a sample keeps
--     its history instead of failing.

CREATE TABLE sample (
  stssn             varchar(25) PRIMARY KEY,
  species           varchar(2) NOT NULL DEFAULT 'u',
  gamm_id           text,
  strand_date       date,  -- nullable: 5 legacy rows have no valid date
  strand_scl        double precision,
  strand_ccl        double precision,
  strand_scw        double precision,
  sex               varchar(1) NOT NULL DEFAULT 'u',
  state             varchar(2),
  decomposition     smallint,
  collaborator      varchar(255),
  processed_bone    text,
  rings_consensus   smallint,
  annulus_consensus double precision,
  humerus_diameter  double precision,
  entered_by        uuid  -- FK added in 0002
);
CREATE INDEX sample_entered_by_idx ON sample (entered_by);

CREATE TABLE note (
  note_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_type  varchar(45) NOT NULL,
  contents   text NOT NULL,
  date       timestamptz,
  left_by    uuid,  -- FK added in 0002
  for_sample varchar(45) REFERENCES sample (stssn)
);
CREATE INDEX note_left_by_idx ON note (left_by);
CREATE INDEX note_for_sample_idx ON note (for_sample);

CREATE TABLE alt_id (
  alt_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  other_id varchar(45) NOT NULL,
  stssn    varchar(25) NOT NULL REFERENCES sample (stssn)
);
CREATE INDEX alt_id_stssn_idx ON alt_id (stssn);

CREATE TABLE audit_log (
  log_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modified_at   timestamptz NOT NULL,
  operation     varchar(45) NOT NULL,
  old_value     text NOT NULL,
  new_value     text NOT NULL,
  related_stssn varchar(25),  -- no FK: history outlives a deleted sample
  modified_by   uuid,  -- FK added in 0002; NULL = changed from the SQL editor
  change_note   integer REFERENCES note (note_id)
);
CREATE INDEX audit_log_related_stssn_idx ON audit_log (related_stssn);
CREATE INDEX audit_log_modified_by_idx ON audit_log (modified_by);
CREATE INDEX audit_log_change_note_idx ON audit_log (change_note);

CREATE TABLE consensus_image (
  image_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_folder varchar(2083) NOT NULL,
  raw_image    varchar(2083) NOT NULL UNIQUE,
  of_stssn     varchar(25) NOT NULL REFERENCES sample (stssn)
);
CREATE INDEX consensus_image_of_stssn_idx ON consensus_image (of_stssn);

CREATE TABLE extra_sample (
  extra_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sample_type varchar(45) NOT NULL,
  location    varchar(45) NOT NULL,
  processed   varchar(1) NOT NULL,
  side        varchar(45),
  stssn       varchar(25) NOT NULL REFERENCES sample (stssn)
);
CREATE INDEX extra_sample_stssn_idx ON extra_sample (stssn);

CREATE TABLE age_reading (
  stssn   varchar(25) NOT NULL REFERENCES sample (stssn),
  user_id uuid NOT NULL,  -- FK added in 0002
  rings   integer NOT NULL,
  annulus double precision NOT NULL,
  note    integer REFERENCES note (note_id),
  PRIMARY KEY (stssn, user_id)
);
CREATE INDEX age_reading_user_id_idx ON age_reading (user_id);
CREATE INDEX age_reading_note_idx ON age_reading (note);


